### ISSUE TITLE
NoSlowDown False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#1]
Issue Information
Glare version: 1.2.4
Spigot version: 1.8.8
Client's version: 1.8.9

Video of false positive: obs being stupid and wont capture my screen
How/when does this happen: if your holding a sword or something that slows you down the switch to a different slot in your hotbar like your sword is in slot 1 your blocking and walking then switch to slot 2 you will false NoSlowDown

Link to config.yml file: default?
Other information:

**Comment by Foulest** [comment]
Will be fixed in v1.2.5.
