### ISSUE TITLE
Debug messages left in console?

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#11]
## Issue Information
**Glare version**: 1.2.5
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: in console it shows when you flag checks the y diff and the velocity so i was just guessing its debug messages left by accident 
**Any possible links to your issue**:  ?
**How/when does this happen**: in console it shows when you flag checks the y diff and the velocity so i was just guessing its debug messages left by accident 
**Other information**:

**Comment by Foulest** [comment]
Fixed. Please remove the old version and check Spigot.
