### ISSUE TITLE
BroadCasting Ban

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#12]
## Issue Information
**Glare version**: 1.2.5-hotfix
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: when you get banned and it broadcasts it the names will not be in the lines sometimes example: https://imgur.com/4sOcukF
**Any possible links to your issue**: ?
**How/when does this happen**: when you get banned and it broadcasts it the names will not be in the lines sometimes example: https://imgur.com/4sOcukF
**Other information**:

**Comment by Foulest** [comment]
Fixed.
