### ISSUE TITLE
Phase Bypass

### ISSUE THREAD

**Issue by tombola46** [Foulest/Glare-Anticheat#14]
## Issue Information
**Glare version**: 1.2.5-HOTFIX
**Spigot version**: 1.8.8
**Client's version**: 1.8.8

**Cheat that bypassed**: Phase
**Link to client used**: http://www.mediafire.com/file/15ignmy1rceg6nq/Skid.zip/file
**Video of bypass**: https://youtu.be/endTGLq30Z0
**Other information**: When using you need to jump and there cant be any block you can hit.

**Comment by Foulest** [comment]
The video is private.

**Comment by Foulest** [comment]
Fixed.
