### ISSUE TITLE
Teleport Bypass

### ISSUE THREAD

**Issue by tombola46** [Foulest/Glare-Anticheat#15]
## Issue Information
**Glare version**: 1.2.5-HOTFIX
**Spigot version**: 1.8.8
**Client's version**: 1.8.8

**Cheat that bypassed**: Teleport
**Link to client used**: http://www.mediafire.com/file/15ignmy1rceg6nq/Skid.zip/file
**Video of bypass**: https://youtu.be/eMVJ8pn-jqk
**Other information**: Cant be used on skywars,bedwars,etc. Working only on ground as in the video

**Comment by Foulest** [comment]
This isn't a "bypass" per-se; it doesn't bypass when teleporting to and from islands.
It's essentially a Blink cheat. Here's a video: https://i.imgur.com/legZPkX.mp4
