### ISSUE TITLE
Config Options, NetFrequence, more Server Support

### ISSUE THREAD

**Issue by Jakaboii** [Foulest/Glare-Anticheat#16]
**What checks/features do you need?:**
It has very little config, I feel like with anticheats you need quite a bit of config

Take [cardinal anticheat](https://www.spigotmc.org/resources/cardinal-anticheat-community-edition-1-8-x.72084/) and [matrix anticheat](https://www.spigotmc.org/resources/matrix-anticheat-advanced-cheat-detection-1-8-1-12-1-13-1-14-1-15.64635) as an example

It would also be nice to have more packet checks (they can be falsed when used with a bungee server, but if coded well it won't false) like NetFrequence

And if it could support 1.8 - 1.13.2 that'd also be nice :)

**Comment by Foulest** [comment]
What config options would you like to see?
I'll be working on a 1.12.2 version and skipping the 1.9-1.11 versions, as they aren't popular.
Most spigots use 1.8.9 or 1.12.2.

**Comment by Jakaboii** [comment]
Maybe something to edit all the messages or prefix? I can't remember the config files
Matrix has a github page with the config files though https://github.com/jiangdashao/Matrix-Issues

**Comment by Foulest** [comment]
Added message configuration options. Will be included in 1.2.6. Keeping this open for other packet check functionalities.

**Comment by Foulest** [comment]
Added more configuration.
