### ISSUE TITLE
Slow Criticals Detection (Packet)

### ISSUE THREAD

**Issue by Jakaboii** [Foulest/Glare-Anticheat#18]
## Issue Information
**Glare version**: Latest
**Spigot version**: Paper 1.8.8
**Client's version**: 1.13.2

**Issue information**: When using Criticals (Packet) on [Impact Client](https://impactclient.net) it takes a while to detect it and then just bans me for GroundSpoof
**Any possible links to your issue**: 
**How/when does this happen**: Using Criticals (Packet) on villagers
**Other information**:

**Comment by Foulest** [comment]
Fixed.
