### ISSUE TITLE
Config.yml doesn't save

### ISSUE THREAD

**Issue by Jakaboii** [Foulest/Glare-Anticheat#19]
## Issue Information
**Glare version**: Latest
**Spigot version**: Paper 1.8.8
**Client's version**:

**Issue information**: Anytime I edit config.yml, it just resets upon restart
**Any possible links to your issue**: 
**How/when does this happen**: 
**Other information**:

**Comment by Foulest** [comment]
Please use /glare reload after modifying the config files in the meantime.
Will be fixed soon.

**Comment by Jakaboii** [comment]
OK, thanks
