### ISSUE TITLE
FastLadder (B)

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#2]
Issue Information
Glare version: 1.2.4
Spigot version: 1.8.8
Client's version: 1.8.9

Video of false positive: obs doesn't want to record my screen idk why it use to work
How/when does this happen: sometimes when you take kb by a player next to a wall you will false fastladder but it takes a few times to false it
Other information: obs doesn't want to record my screen idk why it use to work

**Comment by Foulest** [comment]
Fixed.
