### ISSUE TITLE
Jesus Check

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#20]
## Issue Information
**Glare version**: 1.2.5-hotfix
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: i was looking through check list and saw jesus i went on liquidbounce and used liquidwalk mode vanilla and ncp and it didn't flag so i thought it might be bugged
**Any possible links to your issue**: ?
**How/when does this happen**: 
**Other information**:

**Comment by Foulest** [comment]
NCP should flag, but I will work on fixing Jesus Vanilla.

**Comment by Foulest** [comment]
Fixed.
