### ISSUE TITLE
NoWeb Check

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#21]
## Issue Information
**Glare version**: 1.2.5-hotfix
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: same with the jesus check i tried noweb on liquidbounce and it worked just fine so i mean guessing its broken?
**Any possible links to your issue**: ?
**How/when does this happen**: 
**Other information**:

**Comment by Foulest** [comment]
Fixed all NoWeb bypasses with a new movement improvement.
Also merged NoWeb with NoSlowdown.
