### ISSUE TITLE
NoWeb vl?

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#26]
## Issue Information
**Glare version**: 1.2.6
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: theres no like out of 3 its just 0 so it goes up idk if thats a bug or what but i thought it was weird https://imgur.com/wDzLN3l
**Any possible links to your issue**: ?
**How/when does this happen**: 
**Other information**:

**Comment by Foulest** [comment]
Fixed.
