### ISSUE TITLE
Movement Patterns

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#27]
Issue Information
**Glare version**: 1.2.6
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Plugin name**: GadgetsMenu
**Plugin version**: 4.3.29 (latest)

**Video of incompatibility**: obs being stupid
**How/when does this happen**: if you go into the star menu go on gadgets then go on musical and click disco ball gadget it makes it play music and makes you do like mini jumps to kinda be like a dancing theme and it falses movement patterns
**Other information**: Link to plugin https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-15.10885/

**Comment by Foulest** [comment]
Fixed.

**Comment by coolpvpv1** [comment]
> Fixed.

btw you should close those old milestones you had for 1.2.5 and 1.2.6
