### ISSUE TITLE
FastLadder (B) False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#28]
## Issue Information
**Glare version**: 1.2.6
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Video of false positive**: obs being stupid
**How/when does this happen**: sometimes when you sprint and spam jump up stairs that go along ways up you will falst FastLadder (B) Alot
**Other information**:

**Comment by Foulest** [comment]
Fixed.
