### ISSUE TITLE
Speed (A)

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#29]
## Issue Information
**Glare version**: 1.2.6
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Video of false positive**: 
**How/when does this happen**: if you have water going down in a line https://i.badlion.net/UtP2Hf7Vpz4Jr6LXHgxcee.png and have depthstrider 3 boots on and go down it you will false Speed (A) a ton
**Other information**:

**Comment by Foulest** [comment]
Fixed.
