### ISSUE TITLE
Hclip (Sometimes) And Speed A

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#3]
Issue Information
Glare version: 1.2.4 
Spigot version: 1.8.8
Client's version: 1.8.9

Video of false positive: obs being stupid and wont record my screen yet it records my second screen where minecraft isn't on
How/when does this happen: if you have essentialsx and do like /speed 10 it will make you go fast to false hclip but if you do like /speed 5 it will just false speed a
Other information: link to essentialsx https://www.spigotmc.org/resources/essentialsx.9089/

**Comment by coolpvpv1** [comment]
opps meant to make it with the tag incompatible but i forgot xd

**Comment by Foulest** [comment]
Fixed.
