### ISSUE TITLE
Config & checks.yml

### ISSUE THREAD

**Issue by Jakaboii** [Foulest/Glare-Anticheat#30]
**What checks/features do you need?:**
It would be nice if you could put the `checks:` section in the config into it's own file called checks.yml and add a feature called `/glare config` where it opens up a GUI in which you can edit the checks.yml file in-game
It'd also be nice to have an option to edit the broadcast message (which sometimes "breaks", it sends the ------------ twice before it sends the actual message)
And you could also add some other features in the GUI, like a "Whitelist" option, that shows all online players and when you click it, their name turns a bold red and that means they won't be checked by the anticheat, then when you click it again, their name turns an italic grey meaning they will be checked

**Comment by Foulest** [comment]
The broadcasting is fixed in version 1.2.6.
I might not split the config.yml file up, as there aren't many options above the checks.yml file.
