### ISSUE TITLE
Criticals (Packet)

### ISSUE THREAD

**Issue by Jakaboii** [Foulest/Glare-Anticheat#31]
## Issue Information
**Glare version**: Latest
**Spigot version**: Paper 1.8.8 (ViaVersion latest)
**Client's version**: 1.12.2

**Cheat that bypassed**: Criticals (Packet)
**Link to client used**: [Impact Client](https://impactclient.net)
**Video of bypass**: https://streamable.com/fcu7d
**Other information**:

**Comment by Foulest** [comment]
Already fixed.
