### ISSUE TITLE
Lots of checks

### ISSUE THREAD

**Issue by Jakaboii** [Foulest/Glare-Anticheat#32]
## Issue Information
**Glare version**: Latest
**Spigot version**: Spigot 1.8
**Client's version**: 1.8

**Cheat that bypassed**: Fly, Speed, Nofall, KillAura, NoSwing, Jesus, Fucker, NoClip and Vanilla Spider
**Link to client used**: Custom
**Video of bypass**: Don't have
**Other information**:
The info is according to another AC Dev who tested Glare

**Comment by Foulest** [comment]
Well, this is incredibly unhelpful.
Re-report this if you have video proof.

**Comment by Jakaboii** [comment]
He uploaded some to youtube, even though he sent it in the Discord, I'm still gonna put it here so I know when it's fixed or whatever
https://www.youtube.com/watch?v=c0egXAXkE8g
