### ISSUE TITLE
2 message issues

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#33]
## Issue Information
**Glare version**: 1.2.6
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: when you get banned for reach it has the value next to it which kinda helps cheaters find a bypass / right point to lower there reach and the ban in chat is fixed the names in the lines but the was banned for cheating message next to it hits the name of the player example https://imgur.com/uWlAYXb
**Any possible links to your issue**: 
**How/when does this happen**: 
**Other information**:

**Comment by Foulest** [comment]
Fixed.
