### ISSUE TITLE
Bypassing Speed, Fly and Killaura

### ISSUE THREAD

**Issue by DogsDev** [Foulest/Glare-Anticheat#34]
## Issue Information
**Glare version**: 1.2.6
**Spigot version**: 1.8.8
**Client's version**: 1.8.8

**Cheat that bypassed**: Fly, Speed and KillAura
**Link to client used**:  private message me on discord exsloding dogs#8533
**Video of bypass**: my pc is really bad but ill be happy to show you on my test server
**Other information**: nope

**Comment by Foulest** [comment]
Test on latest version.
