### ISSUE TITLE
Movement Patterns

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#4]
Issue Information
**Glare version**: 1.2.4
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Video of false positive**: obs being stupid
**How/when does this happen**: if your in gamemode and hold w up in the air and you hit sneak sometimes it will false Movement Patterns i was building something to see if it would false something and accidentally found this false flag xd
**Other information**:

**Comment by coolpvpv1** [comment]
also happens in spectator mode

**Comment by Foulest** [comment]
Fixed.
