### ISSUE TITLE
Some Weird Bug?

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#5]
Issue Information
**Glare version**: 1.2.4
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: if your on fire and step on a slab it like sets you back but doesn't set off any alerts?
**Any possible links to your issue**: idk?
**How/when does this happen**: if your on fire and step on a slab it like sets you back but doesn't set off any alerts?
**Other information**: idk

**Comment by Foulest** [comment]
Fixed.
