### ISSUE TITLE
Nofall

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#7]
## Issue Information
**Glare version**: 1.2.4
**Spigot version**: 1.8.8
**Client's version**: b70 (Latest)

**Cheat that bypassed**: Nofall mode NoGround basically lifts you off the ground to enough where when you fall your like above the ground so it doesn't register the damage or whatever
**Link to client used**: https://liquidbounce.net/download
**Video of bypass**: obs likes being stupid
**Other information**:

**Comment by Foulest** [comment]
Fixed.
