### ISSUE TITLE
InventoryMove

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#8]
## Issue Information
**Glare version**: 1.2.4
**Spigot version**: 1.8.8
**Client's version**: b70 (latest)

**Cheat that bypassed**: inventorymove mode aacadditionpro
**Link to client used**: https://liquidbounce.net/download
**Video of bypass**: obs being stupid
**Other information**:

**Comment by Foulest** [comment]
This doesn't bypass for me: 
https://i.imgur.com/ZZYLeVz.mp4

**Comment by coolpvpv1** [comment]
> This doesn't bypass for me:
> https://i.imgur.com/ZZYLeVz.mp4

weird might be a issue for me only ill close this issue
