### ISSUE TITLE
You Cant Ride Animals

### ISSUE THREAD

**Issue by coolpvpv1** [Foulest/Glare-Anticheat#9]
## Issue Information
**Glare version**: 1.2.4
**Spigot version**: 1.8.8
**Client's version**: 1.8.9

**Issue information**: when you try to get on a horse it will kick you off instantly same with a pig with a saddle on it
**Any possible links to your issue**: ?
**How/when does this happen**: when you try to get on a horse it will kick you off instantly same with a pig with a saddle on it
**Other information**:

**Comment by Foulest** [comment]
Fixed.
